# Generated by Django 2.2.7 on 2019-11-13 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='end_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='start_time',
            field=models.DateTimeField(null=True),
        ),
    ]
