# Generated by Django 2.2.7 on 2019-11-25 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testn', '0003_auto_20191111_0803'),
        ('competition', '0002_auto_20191113_0917'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testn.Answer')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='competition.Participant')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testn.Question')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testn.Test')),
            ],
            options={
                'db_table': 'ParticipantSubmission',
            },
        ),
    ]
