# Generated by Django 2.2.7 on 2019-11-28 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0003_submission'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='max_point',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='participant',
            name='points',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
