# Generated by Django 2.2.7 on 2019-11-28 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0004_auto_20191128_1324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='max_point',
        ),
        migrations.AlterField(
            model_name='participant',
            name='points',
            field=models.FloatField(null=True),
        ),
    ]
